language: python
matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true
env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1
install: make setup
script: make test
